### ISSUE TITLE
[Medium] changing the quantity of an item on the shopping cart page has no effect

### ISSUE THREAD

**Issue by leldridg** [leldridg/swesp2024#27]
I realized that changing the quantity of an item on the shopping cart page currently yields no effect. 

This may not exactly be a bug, as I'm not sure we've actually make any steps to implement this feature yet (there are not currently any queries that we can use to update the quantity of an item in the user's cart, as far as I'm aware).

**Comment by hjc2** [comment]
@leldridg is this fixed now on main?

**Comment by hjc2** [comment]
in 989fb17

**Comment by leldridg** [comment]
Yes!
