### ISSUE TITLE
[High] unit tests not working!

### ISSUE THREAD

**Issue by leldridg** [leldridg/swesp2024#28]

**Comment by hjc2** [comment]
@leldridg any progress on unit tests functionality?

**Comment by leldridg** [comment]
@hjc2 Jest tests work now, but I'm not sure if this means we want to resolve this issue or not. We technically have not fixed the unit tests that were written so that they work with the framework.

**Comment by hjc2** [comment]
Thank you for the clarification.

I do not think we should resolve this issue.
 
I just wanted to check in for more info 😌

**Comment by hjc2** [comment]
For now you this issue will remain assigned to you, @leldridg

**Comment by leldridg** [comment]
mosts unit tests are working now, so this issue is going to be closed
